#!/usr/bin/env python

import os
from amyloidAI.run import run

if __name__ == "__main__":

    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--input', help='Input PET file', required=True, type=str)
    parser.add_argument('--anat', help='Input anatomical file (MRI or CT). Optionally used for skullstripping and resampling to MNI space', required=False, type=str)

    args = parser.parse_args()

    # TODO: Use args.anat to prepare PET file

    d = run(args.input)
    print(d)